global_costmap:
  global_frame: world
  robot_base_frame: body
  update_frequency: 2.0
  publish_frequency: 1.0
  transform_tolerance: 0.5
  static_map: true
  rolling_window: false
  plugins:
  - name: static_layer
    type: costmap_2d::StaticLayer
  - name: inflation_layer
    type: costmap_2d::InflationLayer
  static_layer:
    map_topic: /map_confirmed
    subscribe_to_updates: false
    track_unknown_space: true
    unknown_cost_value: -1
  inflation_layer:
    inflation_radius: 0.30
    cost_scaling_factor: 6.0
inflation_layer:
  enabled: true
  inflation_radius: 0.30
  cost_scaling_factor: 6.0
