global_costmap:

  global_frame: map_level
  robot_base_frame: body

  update_frequency: 2.0
  publish_frequency: 1.0

  transform_tolerance: 0.5

  static_map: true
  rolling_window: false

  plugins:

    - name: static_layer
      type: "costmap_2d::StaticLayer"

    - name: inflation_layer
      type: "costmap_2d::InflationLayer"

  static_layer:
    map_topic: /map_confirmed
    subscribe_to_updates: false

  inflation_layer:
    inflation_radius: 0.22
    cost_scaling_factor: 8.0
