local_costmap:
  global_frame: map_level
  robot_base_frame: body
  update_frequency: 8.0
  publish_frequency: 3.0
  transform_tolerance: 0.5
  static_map: false
  rolling_window: true
  width: 6.0
  height: 6.0
  resolution: 0.10
  plugins:
    - {name: static_layer, type: "costmap_2d::StaticLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
  static_layer:
    map_topic: /map_confirmed
    subscribe_to_updates: false
    track_unknown_space: false
    unknown_cost_value: -1
  inflation_layer:
    inflation_radius: 0.42
    cost_scaling_factor: 3.5
